"""Migrate New Password Column

Revision ID: 94780a1917bb
Revises: aaf2c0731d0c
Create Date: 2020-04-28 11:08:33.979652

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '94780a1917bb'
down_revision = 'aaf2c0731d0c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('pass_secure', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'pass_secure')
    # ### end Alembic commands ###
